#:kivy 2.3.1
<FileDialogPopup>:
    BoxLayout:
        orientation: 'horizontal'
        padding: 10
        spacing: 10

        BoxLayout:
            orientation: 'vertical'
            size_hint_x: None
            width: min(self.parent.width * 0.4, 400)
            spacing: 5

            BoxLayout:
                size_hint_y: None
                height: '40dp'
                spacing: 5
                Button:
                    text: 'Parent'
                    on_release: root.go_to_parent()
                Button:
                    text: 'Back'
                    on_release: root.go_back()

            FileChooserListView:
                id: filechooser
                filters: ['*.txt']
                on_selection: root.update_preview(self.selection)
                on_submit: root.load_file()
                multiselect: False
                root.filechooser: self

            BoxLayout:
                size_hint_y: None
                height: '40dp'
                spacing: 5
                Button:
                    text: 'Cancel'
                    on_release: root.dismiss()
                Button:
                    text: 'Load'
                    on_release: root.load_file()

        ScrollView:
            bar_width: '10dp'
            do_scroll_x: False
            on_touch_down: root.preview_double_tap(*args)
            TextInput:
                id: preview
                readonly: True
                font_size: '14sp'
                background_color: 1,1,1,1
                foreground_color: 0,0,0,1
                text: ''
                size_hint_y: None
                height: self.minimum_height
                multiline: True
                word_wrap: True
                cursor_width: 0
                root.preview: self