game:
  bot_diameter: 0.1
  bullet_damage: 10
  independent_models: false
  initial_health: 42
  prompt_augmentation: false
  shield_initial_state: true
  shield_size: 35
  step_length: 0.02
  total_rounds: 2
  turns_per_round: 30
llm:
  augmentation_header_file: assets/prompts/augmentation_header_1.txt
  path: /api/generate
  port_base: 5000
  url: http://localhost
ui:
  font_size: 16
  frame_rate: 60
  primary_color: '#0b0b0b'
  title : BatLLM
