game:
  bullet_damage: 10
  independent_models: true
  initial_health: 42
  prompt_augmentation: false
  shield_size: 35
  total_rounds: 5
  total_turns: 13
ui:
  font_size: 16
  primary_color: '#0b0b0b'
