data:
    saved_sessions_folder: saved_sessions

game:
    independent_models: true
    prompt_augmentation: true

    total_rounds: 3
    turns_per_round: 20

    initial_health: 30
    bot_diameter: 0.1

    bullet_damage: 5
    bullet_step_length: 0.01
    bullet_diameter: 0.2

    shield_initial_state: true
    shield_size: 64
    step_length: 0.02

llm:
    augmentation_header_independent: src/assets/prompts/augmentation_header_independent_1.txt
    augmentation_header_dependent: src/assets/prompts/shared_1.txt

    model: llama3.2:latest
    path: /api/chat
    url: http://localhost
    port: 11434
    debug_requests: false

ui:
    font_size: 16
    frame_rate: 60
    primary_color: "#0b0b0b"
    title: BatLLM
