data:
  saved_sessions_folder: saved_sessions
game:
  bot_diameter: 0.1
  bot_step_length: 0.21
  bullet_damage: 5
  bullet_diameter: 0.2
  bullet_step_length: 0.01
  independent_contexts: true
  initial_health: 30
  prompt_augmentation: true
  shield_initial_state: true
  shield_size: 40
  total_rounds: 2
  turns_per_round: 8
llm:
  debug_requests: false
  model: llama3.2:latest
  num_ctx: 4096
  path: /api/chat
  port: 11434
  system_instructions_augmented_independent: src/assets/system_instructions/augmented_independent_1.txt
  system_instructions_augmented_shared: src/assets/system_instructions/augmented_shared_1.txt
  system_instructions_not_augmented_independent: src/assets/system_instructions/not_augmented_independent_1.txt
  system_instructions_not_augmented_shared: src/assets/system_instructions/not_augmented_shared_1.txt
  url: http://localhost
ui:
  ' primary_color': '#ffffff'
  font_size: 16
  frame_rate: 60
  primary_color: '#0b0b0b'
  title: BatLLM
