data:
  saved_sessions_folder: saved_sessions
game:
  bot_diameter: 0.1
  bullet_damage: 8
  independent_models: true
  initial_health: 33
  prompt_augmentation: true
  shield_initial_state: true
  shield_size: 35
  step_length: 0.02
  total_rounds: 3
  turns_per_round: 20
llm:
  augmentation_header_file: src/assets/prompts/augmentation_header.txt
  path: /api/generate
  port_base: 5000
  url: http://localhost
ui:
  font_size: 16
  frame_rate: 60
  primary_color: '#0b0b0b'
  title: BatLLM
