game:
  total_rounds: 2
  turns_per_round: 8
  independent_contexts: true
  prompt_augmentation: true
  initial_health: 30
  bullet_damage: 5
  bullet_diameter: 0.02
  shield_size: 70
  bot_diameter: 0.1
  bot_step_length: 0.03
  bullet_step_length: 0.01
  shield_initial_state: true
ui:
  font_size: 16
  frame_rate: 60
  confirm_on_exit: true
  prompt_save_on_exit: false
  auto_start_ollama: false
  stop_ollama_on_exit: false
  primary_color: '#0b0b0b'
  title: BatLLM
llm:
  last_served_model: ""
  timeout: null
  model_timeouts: {}
  debug_requests: false
  max_tokens: null
  model: smollm2
  num_ctx: 4096
  num_predict: null
  num_thread: null
  path: /api/chat
  port: 11434
  seed: null
  stop: null
  system_instructions_augmented_independent: src/assets/system_instructions/augmented_independent_1.txt
  system_instructions_augmented_shared: src/assets/system_instructions/augmented_shared_1.txt
  system_instructions_not_augmented_independent: src/assets/system_instructions/not_augmented_independent_1.txt
  system_instructions_not_augmented_shared: src/assets/system_instructions/not_augmented_shared_1.txt
  temperature: null
  top_k: null
  top_p: null
  url: http://localhost
data:
  saved_sessions_folder: saved_sessions
