data:
  saved_sessions_folder: saved_sessions
game:
  bot_diameter: 0.1
  bullet_damage: 5
  bullet_diameter: 0.2
  bullet_step_length: 0.01
  independent_contexts: true
  initial_health: 30
  prompt_augmentation: true
  shield_initial_state: true
  shield_size: 40
  step_length: 0.02
  total_rounds: 1
  turns_per_round: 4
llm:
  augmentation_header_independent: src/assets/prompts/augmentation_header_independent_1.txt
  augmentation_header_shared: src/assets/prompts/shared_1.txt
  debug_requests: true
  model: llama3.2:latest
  num_ctx: 32768
  path: /api/chat
  port: 11434
  url: http://localhost
ui:
  ' primary_color': '#ffffff'
  font_size: 16
  frame_rate: 60
  primary_color: '#0b0b0b'
  title: BatLLM
