#:kivy 2.3.1
<HistoryScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: dp(10)
        spacing: dp(10)

        Label:
            text: "History "
            id: title_label
            font_size: "24sp"
            size_hint_y: None
            height: self.texture_size[1] + dp(10)
            color: 0, 0, 0, 1   

        BoxLayout:
            orientation: "horizontal"

            TextInput:
                id: string_panel
                text: ""
                readonly: False
                font_size: "16sp"
                foreground_color: 0, 0, 0, 1
                background_color: 1, 1, 1, 1
                size_hint_y: 1
                size_hint_x: .5
                padding: dp(10), dp(10)
                cursor_blink: True
                cursor_color: 0, 0, 0, 1
                multiline: True
                scroll_y: 1
                scroll_x: 1

            TextInput:
                id: history_panel
                text: ""
                readonly: False
                font_size: "16sp"
                foreground_color: 0, 0, 0, 1
                background_color: 1, 1, 1, 1
                size_hint_y: 1
                size_hint_x: .5
                padding: dp(10), dp(10)
                cursor_blink: True
                cursor_color: 0, 0, 0, 1
                multiline: True
                scroll_y: 1
                scroll_x: 1

        Button:
            text: "Back"
            font_size: "16sp"
            size_hint_y: None
            height: dp(40)
            on_press: root.go_back_home()

