#:kivy 2.3.1
#:import dp kivy.metrics.dp

<HistoryScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: dp(10)
        spacing: dp(10)

        Label:
            text: "History "
            id: title_label
            font_size: "24sp"
            size_hint_y: None
            height: self.texture_size[1] + dp(10)
            color: 0, 0, 0, 1   

        BoxLayout:
            orientation: "horizontal"

            # — Scrollable Markdown Label for Raw String Panel —
            ScrollView:
                id: scroll_string_panel
                size_hint_x: .5
                size_hint_y: 1
                bar_width: dp(10)
                do_scroll_x: False
                do_scroll_y: True
                scroll_type: ['bars', 'content']

                Label:
                    id: string_panel
                    color: 0, 0, 0, 1  
                    text: ""
                    markup: True
                    valign: 'top'
                    halign: 'left'
                    font_size: '16sp'
                    text_size: self.width - dp(20), None
                    size_hint_y: None
                    height: self.texture_size[1] + dp(20)
                    padding: dp(10), dp(10)
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

            # — Scrollable Markdown Label for History Panel —
            ScrollView:
                id: scroll_history_panel
                size_hint_x: .5
                size_hint_y: 1
                bar_width: dp(10)
                do_scroll_x: False
                do_scroll_y: True
                scroll_type: ['bars', 'content']

                Label:
                    id: history_panel
                    color: 0, 0, 0, 1  
                    text: ""
                    markup: True
                    valign: 'top'
                    halign: 'left'
                    font_size: '16sp'
                    text_size: self.width - dp(20), None
                    size_hint_y: None
                    height: self.texture_size[1] + dp(20)
                    padding: dp(10), dp(10)
                    canvas.before:
                        Color:
                            rgba: 1, 1, 1, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

        Button:
            text: "Back"
            font_size: "16sp"
            size_hint_y: None
            height: dp(40)
            on_press: root.go_back_home()