#:kivy 2.3.1
#:import get_color_from_hex kivy.utils.get_color_from_hex
<HomeScreen>:
    name: "home"
    canvas.before:
        Color:
            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout: # main, footer
        orientation: "vertical"
        padding: 0
        spacing: 0
        canvas.before:
            Color:                              
                rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])                    
            Rectangle:
                pos: self.pos
                size: self.size
                                      
        BoxLayout: # above footer, split into 3 columns: prompts, commands, game
            orientation: "horizontal"
            size_hint_y: 0.85
            padding: 0
            spacing: 0

            canvas.before:
                Color:                              
                    rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])                    
                Rectangle:
                    pos: self.pos
                    size: self.size
          
            BoxLayout:   # The first column column is divided in 10, 5 per player            
                orientation: "vertical"
                size_hint_x: 0.306  
                padding: 0, 1, 1, 1
                spacing: 1

                canvas.before:
                    Color:                                                      
                        rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])
                    Rectangle:
                        pos: self.pos
                        size: self.size

                Label:  # "Player One"
                    text: "  [b]Player One[/b]"
                    markup: True                                                      
                    color: 0, 0, 0, 1
                    size_hint_y: None
                    size_hint_x: 1
                    
                    height: "48dp"
                    text_size: self.width, self.height
                    font_size: "16sp"
                    valign: "middle"
                    halign: "left"       
                    canvas.before:
                        Color:                              
                            rgba: .67, .75, .87, 1  # Header "Player One"
                        Rectangle:
                            pos: self.pos
                            size: self.size                                                         

                ScrollView: # Prompt history 1
                    size_hint: (1, .5)
                    bar_width: 20
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content']                     
                    
                    TextInput:
                        padding: 20, 20
                        id: prompt_history_player_1
                        text:""                             
                        multiline: True
                        readonly: True                        
                        height: self.minimum_height
                        size_hint_y: 1
                        size_hint_x: 1
                        scroll_y: 1
                        cursor_blink: True                        
                        background_color: .8, .88, 1, 1 # History 1                        
                        foreground_color: 0, 0, 0, 1 
                        background_normal: ""
                        background_down: ""  
                        
                
                BoxLayout: # Prompt History 1 Buttons
                    orientation: "horizontal"
                    height: "20dp"
                    padding: 0, 1, 0, 1
                    spacing: 1
                    size_hint_y: None

                    canvas.before:
                        Color:                              
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])   # behind the arrow buttons 1                                                    
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Button:
                        background_color: 0.682, 0.722, 0.804, 1
                        background_normal: "" # necessary for colours to work
                        background_down: ""  
                        text: "[b]<[/b]"
                        markup: True                        
                        on_press: root.rewind_prompt_history(1)
                    Button:
                        background_color: 0.752, 0.762, 0.834, 1
                        background_normal: ""
                        background_down: ""   
                        text: "[b]v[/b]"
                        markup: True
                        on_press: root.copy_prompt_history_selected_text(1)
                    Button:
                        background_color: 0.682, 0.722, 0.804, 1
                        background_normal: ""
                        background_down: ""  
                        text: "[b]>[/b]"
                        markup: True
                        on_press: root.forward_prompt_history(1)

                ScrollView: # Prompt Text Input 1
                    size_hint: (1, .5)
                    bar_width: 20
                    do_scroll_x: False
                    do_scroll_y: True                    
                    scroll_type: ['bars', 'content'] 

                    TextInput:
                        padding: 20, 20
                        id: prompt_player_1                                            
                        hint_text: ""
                        multiline: True
                        readonly: False
                        size_hint_y: 1
                        scroll_y: 1
                        height: self.minimum_height                        
                        cursor_blink: True                                      
                        background_color: .79, .87, .99, 1 # input 1
                        foreground_color: 0, 0, 0, 1 
                        background_normal: ""
                        background_down: ""  
                                    

                BoxLayout: # Prompt buttons 1
                    orientation: "horizontal"
                    size_hint_y: None
                    height: "30dp"
                    padding: 0, 1, 0, 5
                    spacing: 2

                    canvas.before:
                        Color:                              
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])   # behind the prompt buttons 1                                                    
                        Rectangle:
                            pos: self.pos
                            size: self.size
                                       
                    Button:
                        background_color: .6, .5, .4, 1
                        background_normal: ""
                        background_down: ""  
                        text: "Submit"
                        bold: 1
                        on_press: root.submit_prompt(1)

                    Button:
                        background_color: .4, .5, .6, 1
                        background_normal: ""
                        background_down: ""  
                        text: "Load"
                        bold: 1
                        on_press: root.load_prompt(1)

                    Button:
                        background_color: .4, .6, .5, 1
                        background_normal: ""
                        background_down: ""   
                        text: "Save"
                        bold: 1
                        on_press: root.save_prompt(1)


                Label: # "Player Two"
                    text: "  [b]Player Two[/b]"
                    markup: True
                    color: 0, 0, 0, 1
                    size_hint_y: None
                    height: "48dp"
                    text_size: self.width, self.height
                    font_size: "16sp"
                    valign: "middle"
                    halign: "left"    
                    canvas.before:
                        Color:                              
                            rgba: 0.86, 0.73, 0.91, 1 # Header "Player Two"                             	
                        Rectangle:
                            pos: self.pos
                            size: self.size
                        
                                   
                ScrollView: # Prompt history 2
                    size_hint: (1, .5)
                    bar_width: 20
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content'] 

                    TextInput:
                        padding: 20, 20
                        id: prompt_history_player_2                        
                        text:""                             
                        multiline: True
                        readonly: True                        
                        height: self.minimum_height
                        size_hint_y: 1
                        scroll_y: 1
                        cursor_blink: True                        
                        background_color: 0.99, 0.87, 1, 1 # History 2                        
                        foreground_color: 0, 0, 0, 1
                        background_normal: ""
                        background_down: ""  
                                        
                BoxLayout: # Prompt History 2 Buttons
                    orientation: "horizontal"
                    height: "20dp"
                    padding: 0, 1, 0, 1
                    spacing: 1
                    size_hint_y: None

                    canvas.before:
                        Color:                              
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])   # behind the arrow buttons 2                                                   
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Button:
                        background_color: 0.804, 0.722, 0.682, 1
                        background_normal: "" # necessary for colours to work
                        background_down: ""  
                        text: "[b]<[/b]"
                        markup: True                        
                        on_press: root.rewind_prompt_history(2)
                    Button:
                        background_color: 0.834, 0.762, 0.752, 1
                        background_normal: ""
                        background_down: ""   
                        text: "[b]v[/b]"
                        markup: True
                        on_press: root.copy_prompt_history_selected_text(2)
                    Button:
                        background_color: 0.804, 0.722, 0.682, 1
                        background_normal: ""
                        background_down: ""  
                        text: "[b]>[/b]"
                        markup: True
                        on_press: root.forward_prompt_history(2)

                ScrollView: # Prompt Text Input 2
                    size_hint: (1, .5)
                    bar_width: 20
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content'] 

                    TextInput:
                        padding: 20, 20
                        id: prompt_player_2                                                
                        hint_text: ""
                        multiline: True
                        readonly: False
                        size_hint_y: 1
                        scroll_y: 1
                        height: self.minimum_height                        
                        cursor_blink: True                          
                        background_color: 0.98, 0.86, .99, 1 # input 2  
                        foreground_color: 0, 0, 0, 1     
                        background_normal: ""
                        background_down: ""                                 

                BoxLayout: # Prompt buttons 2
                    orientation: "horizontal"
                    size_hint_y: None
                    height: "30dp"
                    padding: 0, 1, 0, 0
                    spacing: 2

                    canvas.before:
                        Color:                              
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])   # behind the prompt buttons 2
                        Rectangle:
                            pos: self.pos
                            size: self.size
                                       
                    Button:
                        background_color: .6, .5, .4, 1
                        background_normal: ""
                        background_down: ""  
                        text: "Submit"
                        bold: 1
                        on_press: root.submit_prompt(2)

                    Button:
                        background_color: .4, .5, .6, 1
                        background_normal: ""
                        background_down: ""  
                        text: "Load"
                        bold: 1
                        on_press: root.load_prompt(2)

                    Button:
                        background_color: .4, .6, .5, 1
                        background_normal: ""
                        background_down: ""   
                        text: "Save"
                        bold: 1
                        on_press: root.save_prompt(2)

           
            BoxLayout:  # The second column is divided in 4, 2 per player: Commands and Output History                
                orientation: "vertical"
                size_hint_x: 0.10 
                size_hint_y: 1          
                padding: 0, 1, 0, 1   
                spacing: 1
                
                canvas.before:
                    Color:
                        rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])                        
                    Rectangle:  
                        pos: self.pos
                        size: self.size
                    
                BoxLayout: # Player 1's commands and output history
                    orientation: "vertical"
                    padding: 1, 0, 1, 5
                    spacing: 1
                    canvas.before:
                        Color:                           
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])     
                        Rectangle:
                            pos: self.pos
                            size: self.size
                        
                    Label: # Title "Commands" 1
                        size_hint_x: 1
                        size_hint_y: None                        
                        text: "Commands"
                        markup: True
                        halign: "left"                                                        
                        color: 0, 0, 0, 1    
                        height: "48dp"
                        canvas.before:
                            Color:                                                                                             
                                rgba: .68, .76, .88, 1   # command one         
                            Rectangle:
                                pos: self.pos
                                size: self.size      
                                                        
                    
                    ScrollView: # LLM output parsed by Bot 1
                        size_hint: (1, 1)
                        bar_width: 20                        
                        do_scroll_x: False
                        do_scroll_y: True                    
                        scroll_type: ['bars', 'content']                                             
                        
                        TextInput:
                            padding: 20, 20
                            id: output_history_player_1                               
                            text: ""
                            spacing: 10
                            multiline: True
                            readonly: True
                            height: self.minimum_height
                            size_hint_y: 1
                            size_hint_x: 1
                            scroll_y: 1
                            cursor_blink: True
                            background_color: .75, .83, .95, 1 # Output 1
                            foreground_color: 0, 0, 0, 1 
                            background_normal: ""
                            background_down: ""  
                                                                                    


                BoxLayout: # Player 2's commands and output history                    
                    orientation: "vertical"                            
                    padding: 1, 0, 1, 0
                    spacing: 1

                    canvas.before:
                        Color:                        
                            rgba: get_color_from_hex(app.theme_colors['color.prompt_text'])   
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Label: # Title "Commands" 2
                        size_hint_x: 1
                        size_hint_y: None                        
                        text: "Commands"
                        markup: True
                        halign: "left"                            
                        color: 0, 0, 0, 1    
                        height: "48dp"
                        canvas.before:
                            Color:                                
                                rgba: 0.86, 0.73, 0.91, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size                                               
                            

                    ScrollView: # LLM output parsed by Bot 2                       
                        bar_width: 20
                        do_scroll_x: False
                        do_scroll_y: True                    
                        scroll_type: ['bars', 'content']                                                 
                        
                        TextInput:
                            padding: 20, 20
                            id: output_history_player_2
                            text: ""
                            spacing: 10
                            multiline: True
                            readonly: True
                            height: self.minimum_height
                            size_hint_y: 1
                            size_hint_x: 1
                            scroll_y: 1
                            cursor_blink: True
                            background_color: 0.9, 0.85, 0.95, 1  # Output 2
                            foreground_color: 0, 0, 0, 1 
                            background_normal: ""
                            background_down: ""                        
                                                                                                                
                
           
            BoxLayout:  # Third Column (game area) is also divided in three.
                orientation: "vertical"
                padding: 1
                spacing: 1
                canvas.before:
                    Color:                        
                        rgba: get_color_from_hex(app.theme_colors['color.prompt_text']) 
                    Rectangle:
                        pos: self.pos
                        size: self.size
                

                BoxLayout:  # Header with two labels
                    orientation: "horizontal"
                    size_hint: 1, None
                    height: "48dp"                      
                    padding: 60, 0, 0, 0
                    spacing: 0
                    canvas.before:
                        Color:                              
                            rgba: .7, .73, .7, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                   
                    Label:
                        font_size: "20sp"
                        text: "[b]BatLLM[/b]"
                        
                        size_hint_x: None                    
                        size_hint_y: None
                        width: 250
                        
                        id: header_label                                 
                        markup: True

                        halign: "left"
                        valign: "middle"

                        color: .2, .2, .2, 1
                        text_size: self.width, self.height


                    Label:
                        id: game_title_label
                        font_size: "16sp"
                        
                        size_hint_x: 1
                        size_hint_y: None
                                                
                        markup: True

                        halign: "left"
                        valign: "middle"

                        color: .3, .3, .3, 1                    
                        text_size: self.width, self.height

                    

                AnchorLayout:
                    anchor_x: "center"
                    anchor_y: "center"                    
                    canvas.before:
                        Color:                              
                            rgba: .8, .83, .8, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size                                                                    
                    GameBoard:
                        id: game_board
                        size_hint: 1, 1



                                
       
        BoxLayout:  # Footer
            orientation: "horizontal"            
            size_hint_y: None
            height: "40dp"
            padding: "0dp"
            font_size: "16sp"

            canvas.before:
                Color:
                    rgba: get_color_from_hex(app.theme_colors['color.footer_bg'])
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "https://github.com/krahd/BatLLM"
                font_size: "16sp"
                halign: "left"
                color: 1,1,1,1
                size_hint_x: 2

            Label:
                text: "BatLLM 0.0.1"
                font_size: "16sp"
                color: 1, 1, 1, 1
                halign: "left"
                size_hint_x: 4
                

            Button:
                text: "Settings"
                font_size: "16sp"
                on_press: root.go_to_settings_screen()

            Button:
                text: "New Game"
                font_size: "16sp"
                on_press: root.start_new_game()

            Button:
                text: "Save Session"
                font_size: "16sp"
                on_press: root.save_session()  