
#:kivy 2.3.1
<HomeScreen>:
    name: "home"
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout: # header, main, footer
        orientation: "vertical"
        padding: 0
        spacing: 0
      
        BoxLayout:   # header
            size_hint_y: None
            halign: "left"
            height: "40dp"
            padding: "0dp"
            spacing: "0dp"
            canvas.before:
                Color:
                    rgba: .8, .88, 1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: "BatLLM"
                padding: 10
                bold: True
                color: .1,.1,.1, 1
                font_size: "20sp"
                halign: "left"
                valign: "middle"
                size_hint_x: None
                width: self.texture_size[0] + 20
       
        BoxLayout: # main window
            orientation: "horizontal"
            size_hint_y: 0.85
          
            BoxLayout:   # First Column (prompts)
                orientation: "vertical"
                size_hint_x: 0.306  
                padding: 0, 0
                canvas.before:
                    Color:                              
                        rgba: 1,0,1,0
                    Rectangle:
                        pos: self.pos
                        size: self.size

                BoxLayout: # text prompt title 1
                    orientation: "horizontal"
                    halign: "left"
                    height: "48dp"
                    size_hint_y: None
                    padding: 50, 15
                    canvas.before:
                        Color:                              
                            rgba: .8, .88, 1, .7
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Label:
                        text: "Player One's Prompting Area"
                        bold: 1                                                             
                        color: 0, 0, 0, .8
                        halign: "left"
                        padding: 0
                    
                    Label:
                        text:""
                        size_hint_x: .9

                ScrollView: # prompt history 1
                    size_hint: (1, .5)
                    bar_width: 10
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content'] 
                    background_color: 1, 1, 1, 1                    

                    TextInput:
                        padding: 20, 10
                        id: prompt_history_player_1
                        text:""                             
                        multiline: True
                        readonly: True
                        size_hint_y: None
                        height: self.minimum_height
                        scroll_y: 1
                        cursor_blink: True
                        bar_width: 10
                        background_color: 1, 1, 1, 1  # white
                        foreground_color: 0, 0, 0, 1  # black text
                        background_normal: ""        # removes border image
                        background_active: ""        # removes active border image
                
                BoxLayout: # buttons
                    orientation: "horizontal"
                    height: "20dp"
                    size_hint_y: None
                    Button:
                        text: "<"
                        on_press: root.rewind_prompt_history(1)
                    Button:
                        text: "copy"
                        on_press: root.copy_prompt_history_selected_text(1)
                    Button:
                        text: ">"
                        on_press: root.forward_prompt_history(1)

                ScrollView: # prompt input 1
                    size_hint: (1, .5)
                    bar_width: 10
                    do_scroll_x: False
                    do_scroll_y: True                    
                    scroll_type: ['bars', 'content'] 

                    TextInput:
                        id: prompt_player_1
                        #text: ""
                        text: "reply with M, just the single letter. your response should be literally \"M\" (without the \")\""
                        hint_text: "New prompt"
                        multiline: True
                        readonly: False
                        size_hint_y: None
                        height: self.minimum_height
                        scroll_y: 1
                        cursor_blink: True
                        bar_width: 10   
                                    

                BoxLayout: # submit button
                    size_hint_y: None
                    height: "30dp"
                    spacing: 5                    
                    Button:
                        background_color: .9, .2, .2, 1
                        text: "Submit"
                        on_press: root.submit_prompt(1)
                        bold: 1

                Label:
                    text:""
                    height: "8dp"
                    size_hint_y: None

                BoxLayout: # text prompt title 2
                    orientation: "horizontal"
                    halign: "left"
                    height: "48dp"
                    size_hint_y: None
                    padding: 50, 15
                    canvas.before:
                        Color:                              
                            rgba: .8, 65, .9, .7
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Label:
                        text: "Player Two's Prompting Area"
                        bold: 1                                                             
                        color: 0, 0, 0, .8
                        halign: "left"
                        padding: 0
                    
                    
                    Label:
                        text:""

               

                ScrollView: # prompt history 2
                    size_hint: (1, .5)
                    bar_width: 10
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content'] 
                    background_color: 1, 1, 1, 1

                    TextInput:
                        id: prompt_history_player_2                        
                        text:""                             
                        multiline: True
                        readonly: True
                        size_hint_y: None
                        height: self.minimum_height
                        scroll_y: 1
                        cursor_blink: True
                        bar_width: 10
                        background_color: 1, 1, 1, 1  # white
                        foreground_color: 0, 0, 0, 1  # black text
                        background_normal: ""        # removes border image
                        background_active: ""        # removes active border image
                
                BoxLayout:
                    orientation: "horizontal"
                    height: "20dp"
                    size_hint_y: None
                    Button:
                        text: "<"
                        on_press: root.rewind_prompt_history(2)
                    Button:
                        text: "copy"
                        on_press: root.copy_prompt_history_selected_text(2)
                    Button:
                        text: ">"
                        on_press: root.forward_prompt_history(2)

                ScrollView: # prompt input 2
                    size_hint: (1, .5)
                    bar_width: 10
                    do_scroll_x: False
                    do_scroll_y: True
                    scroll_type: ['bars', 'content'] 

                    TextInput:
                        id: prompt_player_2                        
                        #text: ""
                        text: "reply with M, just the single letter. your response should be literally \"M\" (without the \")\""
                        hint_text: "New prompt"
                        multiline: True
                        readonly: False
                        size_hint_y: None
                        height: self.minimum_height
                        scroll_y: 1
                        cursor_blink: True
                        bar_width: 10   
                                    

                BoxLayout: # submit button 1
                    size_hint_y: None
                    height: "30dp"
                    spacing: 5                    
                    
                    Button:                        
                        background_color: .9, .2, .2, 1
                        text: "Submit"
                        bold: 1
                        on_press: root.submit_prompt(2)

           
            BoxLayout:  # Second Column (commands histories)
                
                orientation: "vertical"
                size_hint_x: 0.10 
                size_hint_y: 1
                halign: "left"
                padding: 0, 0
                
                canvas.before:
                    Color:
                        rgba: .95, .96, .95, 1
                    Line:
                        width: 1
                        rectangle: self.x, self.y, self.width, self.height
                    
                    Rectangle:
                        pos: self.pos
                        size: self.size
                    
                BoxLayout: # 2 col, play 1 v
                    orientation: "vertical"
                    
                    canvas.before:
                        Color:                           
                            rgba: .95, .96, .95, 1# .8, .88, 1, .5
                        Rectangle:
                            pos: self.pos
                            size: self.size
                        
                    BoxLayout: # title commands 1
                        orientation: "horizontal"
                        height: "48dp"
                        size_hint_y: None
                        padding: 50, 35
                        
                        canvas.before:
                            Color:                                
                                rgba: .8, .88, 1, .5
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        Label:
                            text: "Commands"
                            bold: 1                        
                            halign: "left"                            
                            
                            color: 0, 0, 0, 1
                            size_hint_y: None
                            size_hint_x: None
                            height: "12dp" 
                            
                        Label:
                            size_hint_x: .02

                    
                    
                    ScrollView: # llm output history player 1
                        size_hint: (1, .5) 
                        bar_width: 10
                        do_scroll_x: False
                        do_scroll_y: True                    
                        scroll_type: ['bars', 'content'] 
                        
                        TextInput:
                            padding: 35, 20
                            id: output_history_player_1
                            text: ""
                            multiline: True
                            readonly: False
                            size_hint_y: None  
                            height: self.minimum_height                     
                            scroll_y: 1                
                            cursor_blink: False            
                            bar_width: 10                               
                                                        
                            background_color: .95, .96, .95, 1
                            background_normal: ""        # removes border image
                            background_active: ""        # removes active border image
                   

                Label: # separator
                    text: "."
                    height: "32dp"
                    size_hint_y: None
                


                BoxLayout: # 2 col, play 2, v
                    orientation: "vertical"                    
                    canvas.before:
                        Color:                        
                            rgba: .95, .96, .95, 1
                        Rectangle:
                            pos: self.pos
                            size: self.size


                    BoxLayout: # title commands 2
                        orientation: "horizontal"                        
                        height: "48dp"
                        size_hint_y: None
                        padding: 50, 35
                        canvas.before:
                            Color:                             
                                rgba: .83, 1, .98, 1
                            Rectangle:
                                pos: self.pos
                                size: self.size

                        Label:
                            text: "Commands"
                            bold: 1
                            halign: "left"                            
                            color: 0, 0, 0, 1
                            size_hint_y: None
                            size_hint_x: None
                            height: "12dp" 
                            
                        Label:
                            size_hint_x: .02


                    ScrollView: # llm output history player 2
                        size_hint: (1, .5) 
                        bar_width: 10
                        do_scroll_x: False
                        do_scroll_y: True                    
                        scroll_type: ['bars', 'content'] 
                        
                        TextInput:
                            padding: 35, 20
                            id: output_history_player_2
                            text: ""
                            multiline: True
                            readonly: False
                            size_hint_y: None  
                            height: self.minimum_height                     
                            scroll_y: 1                
                            cursor_blink: False            
                            bar_width: 10                               
                                                        
                            background_color: .95, .96, .95, 1
                            background_normal: ""        # removes border image
                            background_active: ""        # removes active border image
                        
                Label: # separator
                    text: "."
                    height: "24dp"
                    size_hint_y: None                            
                                            
           
            BoxLayout:  # Third Column (game area)
                orientation: "vertical"
                padding: 0, 0   
                
                canvas.before:
                    Color:
                        #rgba: 0, 0, 0, .15
                        rgba: .8,.83,.8,1
                    Rectangle:
                        pos: self.pos
                        size: self.size

                


                BoxLayout:  # Title
                    orientation: "horizontal"             
                    height: "48dp"
                    size_hint_y: None                  
                    size_hint_x: 1          
                    padding: 340, 34
                    canvas.before:
                        Color:                             
                            rgba: 0, 0, 0, .1
                        Rectangle:
                            pos: self.pos
                            size: self.size

                    Label:
                        font_size: "14sp"
                        id: header_label
                        text: ""                        
                        bold: 1
                        halign: "left"
                        color: 0, 0, 0, 1
                        size_hint_y: None
                        size_hint_x: .055
                        height: "12dp" 
                        
                    Label:
                        size_hint_x: .4
                    
                

                GameBoardWidget:
                    id: game_board
                    size_hint_x: 1
                    size_hint_y: 1
                    padding: 0, 0

                   
                                    
       
        BoxLayout:  # Footer
            orientation: "horizontal"
            halign: "left"
            size_hint_y: None
            height: "30dp"
            padding: "0dp"

            canvas.before:
                Color:
                    rgba: 0.3, 0.3, 0.4, 1  
                Rectangle:
                    pos: self.pos
                    size: self.size

            Label:
                text: "https://github.com/krahd/BatLLM"
                halign: "left"
                color: 1,1,1,1
                size_hint_x: 7.4

            Label:
                text: "BatLLM 0.0.1b"
                font_size: "14sp"
                color: 1,1,1,1
                halign: "left"

            Button:
                text: "Settings"
                on_press: root.go_to_settings_screen()

            Button:
                text: "Save game"
                on_press: root.save_game()
           
