
#:kivy 2.3.1
<Overlay@Widget>:  # Hacky temporal overlay widget. It will be removed 
# whev colours move to a properties file which, in turn, will be used by
# the theme manager (which is not implemented yet), nor there is any urgency
# to do so.

    overlay_alpha: 0.0
    desaturation: 0.0
    canvas.before:
        Color:
            rgba: (1 - self.desaturation) + self.desaturation * 0.3, (1 - self.desaturation) + self.desaturation * 0.59, (1 - self.desaturation) + self.desaturation * 0.11, 1
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: 1, 1, 1, self.overlay_alpha
        Rectangle:
            pos: self.pos
            size: self.size

<HomeScreen>:
    name: 'home'
    BoxLayout:
        orientation: 'vertical'

        # Your UI elements go here

    
<HomeScreen>:  # same w/o overlay
    name: "home"   # same w/o overlay
    BoxLayout: # new
        orientation: "vertical" # new
        canvas.before: # tab++
            Color:
                rgba: 0, 0, 0, 1
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout: # # tab++


        Overlay:  # new
        id: overlay # new
        