
%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of Bot.prepare_prompt_submission() of /src/game/bot.py

    participant p1 as prepare_prompt_submission()<br>:Bot


	p1 ->>+ p1: 1: append_prompt_to_history(new_prompt)
	p1 -->>- p1: 1: return value
        