#:import dp kivy.metrics.dp

<SaveDialog>:
    title: "Save Prompt As…"
    size_hint: .8, .8
    auto_dismiss: False

    BoxLayout:
        orientation: "vertical"
        spacing: dp(10)
        padding: dp(10)

        FileChooserListView:
            id: filechooser
            path: root.start_folder
            filters: ["*.txt"]
            dirselect: True

        BoxLayout:
            size_hint_y: None
            height: dp(40)
            spacing: dp(10)

            TextInput:
                id: filename
                multiline: False
                hint_text: "Enter filename"
                size_hint_x: 0.6

            Button:
                text: "Cancel"
                size_hint_x: 0.2
                on_release: root.dismiss()

            Button:
                text: "Save"
                size_hint_x: 0.2
                on_release: root._save()