#:kivy 2.3.1
<SettingsScreen>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # White background
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        padding: dp(40)
        spacing: dp(25)
        size_hint: 0.7, None
        height: self.minimum_height
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        # Titles
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(10)
            padding: 0, dp(80)

            Label:
                text: "BattLLM"
                font_size: sp(44)
                color: 0, 0, 0, 1
                size_hint_y: None
                height: self.texture_size[1]

            Label:
                text: "Game Settings"
                font_size: sp(32)
                color: 0, 0, 0, 1
                size_hint_y: None
                height: self.texture_size[1]

        # Game sliders
        BoxLayout:
            orientation: 'vertical'
            spacing: dp(20)
            size_hint_y: None
            height: self.minimum_height

            # Total Rounds
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Total Rounds"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: rounds_label
                    text: str(int(rounds_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: rounds_slider
                    min: 1
                    max: 10
                    value: root.total_rounds
                    step: 1
                    on_value: rounds_label.text = str(int(self.value))
                    size_hint_x: 0.5
                    cursor_image: "assets/images/slider_gray_image.png"
                    cursor_color: .7, .7, .7, 1
                    

            # Total Turns
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Total Turns"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: turns_label
                    text: str(int(turns_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: turns_slider
                    min: 1
                    max: 40
                    value: root.turns_per_round
                    step: 1
                    on_value: turns_label.text = str(int(self.value))
                    size_hint_x: 0.5
                    cursor_color: .7, .7, .7, 1
                    cursor_image: "assets/images/slider_gray_image.png"

            # Initial Health
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(40)

                Label:
                    text: "Initial Health"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: health_label
                    text: str(int(health_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: health_slider
                    min: 1
                    max: 100
                    value: root.initial_health
                    step: 1
                    on_value: health_label.text = str(int(self.value))
                    size_hint_x: 0.5
                    cursor_color: 0, 0, 0, 1
                    cursor_image: "assets/images/slider_gray_image.png"

            # Bullet Damage
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Bullet Damage"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: damage_label
                    text: str(int(damage_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: damage_slider
                    min: 1
                    max: 10
                    value: root.bullet_damage
                    step: 1
                    on_value: damage_label.text = str(int(self.value))
                    size_hint_x: 0.5
                    cursor_color: .7, .7, .7, 1
                    cursor_image: "assets/images/slider_gray_image.png"

            # Shield Size
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Shield Size (°)"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: shield_label
                    text: str(int(shield_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: shield_slider
                    min: 0
                    max: 90
                    value: root.shield_size
                    step: 1
                    on_value: shield_label.text = str(int(self.value))
                    size_hint_x: 0.5
                    cursor_color: .7, .7, .7, 1
                    cursor_image: "assets/images/slider_gray_image.png"

            # Bot Step Length
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Step Length"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                Label:
                    id: step_label
                    text: str(float(step_slider.value))
                    font_size: sp(20)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.1

                Slider:
                    id: step_slider
                    min: 0.01
                    max: 0.5
                    value: root.bot_step_length
                    step: 0.01
                    on_value: step_label.text = f"{self.value:.2f}"
                    size_hint_x: 0.5
                    cursor_color: .7, .7, .7, 1
                    cursor_image: "assets/images/slider_gray_image.png"

        # Checkbox options
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
     
            spacing: dp(12)

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Independent Models"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: independent_checkbox
                        active: root.independent_contexts
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Prompt Augmentation"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: augmentation_checkbox
                        active: root.prompt_augmentation
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Confirm on Exit"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: confirm_on_exit_checkbox
                        active: root.confirm_on_exit
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Prompt to Save on Exit"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: save_on_exit_checkbox
                        active: root.prompt_save_on_exit
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Start Ollama Automatically on BatLLM Launch"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: auto_start_ollama_checkbox
                        active: root.auto_start_ollama
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                size_hint_y: None
                height: dp(50)

                Label:
                    text: "Stop Ollama Automatically on BatLLM Quit"
                    font_size: sp(22)
                    color: 0, 0, 0, 1
                    size_hint_x: 0.4
                    halign: "left"
                    valign: "middle"
                    text_size: self.size

                AnchorLayout:
                    size_hint_x: 0.6
                    anchor_x: "right"
                    anchor_y: "center"

                    CheckBox:
                        id: stop_ollama_on_exit_checkbox
                        active: root.stop_ollama_on_exit
                        size_hint: None, None
                        size: dp(32), dp(32)
                        background_checkbox_normal: "assets/images/checkbox_off.png"
                        background_checkbox_down: "assets/images/checkbox_on.png"

        # Buttons
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: None
            height: "90dp"
            spacing: dp(12)

            Widget:
                size_hint_x: 0.2

            Button:
                id: cancel_btn
                text: "Cancel"
                font_size: '24sp'
                size_hint: None, None
                width: dp(180)
                height: dp(56)
                color: 1,1,1,1
                background_color:  1, .7, .8, .9

                on_press: root.cancel_and_return()

            Widget:
                size_hint_x: 0.05

            BoxLayout:
                size_hint_x: 0.75
                spacing: dp(12)

                Button:
                    id: default_btn
                    text: "Set as Defaults"
                    font_size: '24sp'
                    size_hint_y: None
                    height: dp(56)
                    color: 1,1,1,1
                    background_color:  .6, .8, .9, .8

                    on_press: root.set_as_defaults()

                Button:
                    id: set_btn
                    text: "Set Temporarily"
                    font_size: '24sp'
                    size_hint_y: None
                    height: dp(56)
                    color: 1,1,1,1
                    background_color: .6, .8, .9, .8

                    on_press: root.set_and_return()

                Button:
                    id: ollama_btn
                    text: "Ollama Config"
                    font_size: '24sp'
                    size_hint_y: None
                    height: dp(56)
                    color: 1,1,1,1
                    background_color: .6, .8, .9, .8

                    on_press: root.go_to_ollama_config_screen()
